const prompt = require('prompt-sync')()
const Characters = require('./class/Characters')

const character1 = new Characters('John', 'Guerreiro', 100)
const character2 = new Characters('Luciano Hulk', 'Mago', 80)
const character3 = new Characters('Pedro', 'Arqueiro', 90)

console.log('----------------------------')
character1.atack()
character1.characterInfos()
console.log('----------------------------')
character2.atack()
character2.characterInfos()
console.log('----------------------------')
character3.atack()
character3.characterInfos()
console.log('----------------------------')